apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inovatech-ingress
  namespace: inovatech
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
  - host: inovatech.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: api.inovatech.local
    http:
      paths:
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: products-service
            port:
              number: 3001
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: orders-service
            port:
              number: 3002
